version: '3.9'

services:
  app:
    container_name: test-junit-app
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./
        target: /home/work
    tty: true
